config/routes.rb
Rails.application.routes.draw do
  resources :businesses
  devise_for :users
  resources :charges
  
  root to: 'businesses#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord
    belongs_to :user
    validates :seller, presence: true
    validates :business_name, presence: true
    validates :industry, presence: true
    validates :location, presence: true
    validates :price, presence: true
    validates :size, presence: true
    validates :inclusions, presence: true
    validates :business_info, presence: true
    # mount_uploader :avatar, AvatarUploader
    mount_uploader :business_image, AvatarUploader

    def self.search(search)
        if search
          where('business_name LIKE ? OR seller LIKE ? OR industry LIKE ? OR location LIKE ? OR size LIKE ? OR inclusions LIKE ? OR business_info LIKE ?', "%#{search.titleize}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
        else
          where(nil)
        end
      end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
has_many :businesses

  # mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
 
  private
  
    def user_not_authorized
      flash[:warning] = "You are not authorized to perform this action."
      redirect_to(request.referrer || root_path)
    end
end

app/controllers/businesses_controller.rb
 class BusinessesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  # GET /businesses
  # GET /businesses.json
  helper_method :sort_column, :sort_direction
  def index
    @businesses = Business.search(params[:search]).order(sort_column + " " +  sort_direction).paginate(:per_page => 6, :page => params[:page])
    authorize @businesses
  end
 
  # GET /businesses/1
  # GET /businesses/1.json
  def show
  end
 
  # GET /businesses/new
  def new
    @business = Business.new
    authorize @business
  end
 
  # GET /businesses/1/edit
  def edit
  end
 
  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)
    @business.user = current_user
    authorize @business
 
    respond_to do |format|
      if @business.save
        UserNotifierMailer.send_signup_email(current_user).deliver
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end
 
  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end
 
  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @business = Business.find(params[:id])
      authorize @business
    end
 
    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:seller, :business_name, :business_image, :industry, :location, :price, :size, :inclusions, :business_info, :user)
    end

    def sort_column
      Business.column_names.include?(params[:sort]) ? params[:sort] : "business_name"
    end
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    before_action :set_item
    def new
    end
    
    def create
      # Amount in cents
      @amount = @business.price*100
    
      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )
    
      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => 'Rails Stripe customer',
        :currency    => 'aud'
      )

      redirect_to businesses_path
    
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end
    private
                  def set_item
                    @business = Business.find(params[:business_id])
                  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def create
      # Create the user from params
      @user = User.new(params[:user])
      if @user.save
        # Deliver the signup email
        UserNotifier.send_signup_email(@user).deliver
        redirect_to(@user, :notice => 'User created')
      else
        render :action => 'new'
      end
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
    def sortable(column, title = nil)
        title ||=column.titleize
        css_class = column == sort_column ? "current #{sort_direction}" : nil
        direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
        link_to title, params.merge(:sort => column, :direction => direction, :page => nil).permit(:param_1, :param_2, :sort, :direction, :page), {:class => css_class}

    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/businesses/_businesses.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<%= will_paginate @businesses %>

app/views/businesses/_form.html.erb
<body class="yel">
<%= form_with(model: business, local: true) do |form| %>
  <% if business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% business.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col -12 edit_pad">
  <div class="field">
    <p class="bb"><%= form.label :seller %></p>
    <p><%= form.text_field :seller %></p>
    
  </div>

  <div class="field">
    <p class="bb"><%= form.label :business_name %></p>
    <p><%= form.text_field :business_name %></p>
  </div>

   <div class="field">
    <p class="bb"><%= form.label :business_image %></p>
    <p><%= form.file_field :business_image %></p>
  </div>

  <div class="field">
    <p class="bb"><%= form.label :industry %></p>
    <p><%= form.text_field :industry %></p>
  </div>

  <div class="field">
    <p class="bb"><%= form.label :location %></p>
    <p><%= form.text_field :location %></p>
  </div>

  <div class="field">
    <p class="bb"><%= form.label :price %></p>
    <p><%= form.number_field :price %></p>
  </div>

  <div class="field">
    <p class="bb"><%= form.label :size %></p>
    <p><%= form.text_field :size %></p>
  </div>

  <div class="field">
    <p class="bb"><%= form.label :inclusions %></p>
    <p><%= form.text_field :inclusions %></p>
  </div>

  <div class="field">
    <p class="bb"><%= form.label :business_info %></p>
    <p><%= form.text_field :business_info %></p>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  </div>
<% end %>
</body>

app/views/businesses/edit.html.erb
<h1>Editing Business</h1>

<%= render 'form', business: @business %>
<div class="col-12 edit_pad">
<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>
</div>

app/views/businesses/index.html.erb
<p id="notice"><%= notice %></p>

<body class="yel">
  <div class="col cust-col d-flex justify-content-around">
      <ul>
        <li class="toggle_bar"> <%= sortable "seller"%> </li>
        <li class="toggle_bar"> <%= sortable "business_name", "Business name"%> </li>
        <li class="toggle_bar"> <%= sortable "industry"%> </li>
        <li class="toggle_bar"> <%= sortable "location"%> </li>
        <li class="toggle_bar"> <%= sortable "inclusions"%> </li>
      </ul>
    </div>
  

  <div class="card-deck">
    <% @businesses.each do |business| %>
      <div class="card">
      <h5 class="card-title custcol font-edit"><%= business.business_name.capitalize! %></h5>
      <div class="container">
      <div class="col">
      <div class="row">
      <div class="col-5">
      <div class="card-img-top"><%= link_to(image_tag(business.business_image.small_thumb.url, alt: 'Image'), business.business_image.url, target: '_blank') if business.business_image? %></div>
      </div>
      <div class="col-6 custcolor">
      <div class="card-body">
        <p class="card-text-cust aleg">Price</p>
        <p class="card-text custcol">$<%= business.price %></p>
        <p class="card-text-cust aleg">Industry</p>
        <p class="card-text custcol"><%= business.industry.titleize %></p>
        <p class="card-text-cust aleg">Inclusions</p>
        <p class="card-text custcol"><%= business.inclusions.titleize %></p>
        <p class="card-text-cust aleg">Location</p>
        <p class="card-text custcol"><%= business.location.titleize %></p>
      </div>
      </div>
      </div>
      </div>
      </div>
      <div class="card-footer">
          <%= business.seller.capitalize! %>
          <%= link_to 'Show', business %>
      </div>
        

      </div>
    <% end %>
    </div>

<%= will_paginate @business%>
<br>

</body>

app/views/businesses/new.html.erb
<h1>New Business</h1>

<%= render 'form', business: @business %>

<div class="col-12 edit_pad">
<%= link_to 'Back', businesses_path %>
</div>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<% item_price = @business.price%>
<body class="yel">
<div class="col-12">
<div class="row">
<h1 class="float-left">
  <%= @business.business_name.titleize %>
</h1>
</div>
</div>

<div class="col-12">
<div class="row">
<ul>
<li class=" toggle_bar1">
  <strong>Industry:</strong>
  <%= @business.industry.titleize %>
</li>

<li class=" toggle_bar1">
  <strong>Location:</strong>
  <%= @business.location.titleize %>
</li>

<li class=" toggle_bar1">
  <strong>Price:</strong>
  $<%= @business.price %>
</li>

<li class=" toggle_bar1">
  <strong>Size:</strong>
  <%= @business.size.titleize %>
</li>

<li class=" toggle_bar1">
  <strong>Inclusions:</strong>
  <%= @business.inclusions.titleize %>
</li>
</ul>
</div>
</div>

<div class="col-12">
<div class="row">
<div class="col-4">
<p>
<%#= image_tag(@business.business_image.url, alt: 'Image') if @business.business_image? %>
<%= link_to(image_tag(@business.business_image.thumb.url, alt: 'Image'), @business.business_image.url, target: '_blank') if @business.business_image? %>
</p>


</div>
<div class="col-4 bb">
<h2 class="bb">
Business info
</h2>
<p class="bb">
<%= @business.business_info.titleize %>
</p>
</div>
<div class="col-1">
</div>
<div class="col-3 bb">
<h2>
Seller Info
</h2>
<p>
  <strong>Seller:</strong>
  <%= @business.seller %>
</p>
</div>
</div>
</div>

<div class="edit_pad">
    <% if user_signed_in? %>
    <%= form_tag charges_path do %>
<%= hidden_field_tag "business_id", "#{@business.id}" %>
 <%= javascript_include_tag 'https://checkout.stripe.com/checkout.js',
   class: 'stripe-button',
   data: {
     key: ENV["PUBLISHABLE_KEY"],
     # total price x 100 because it must be in cents
     amount: item_price*100 ,
     name: "Buy Buy Business",
     description: @business.business_name,
     locale: "auto",
     currency: "aud"
   }
 %>
<% end %>
        <%= link_to 'Destroy', @business, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Edit', edit_business_path(@business) %> |
<%end%>
<%= link_to 'Back', businesses_path %>
</div>
</div>
</body>

app/views/charges/create.html.erb
<body class="yel edit_pad">
<h2>Thanks, you paid <strong>$<%=@business.price%></strong>!</h2>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Buybuybusiness</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
<%= render 'businesses/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/payments.html.erb
<%= form_tag charges_path do %>
<article>
  <% if flash[:error].present? %>
  <div id="error_explanation">
    <p><%= flash[:error] %></p>
  </div>
  <% end %>
  <label class="amount">
  <span>Amount: $<%= @order.price %></span>
  </label>
</article>
<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-description="A month's subscription"
  data-amount="<%= @order.price %>"
  data-locale="auto"></script>
<% end %>